namespace SystemInit.Packages
{
    public static class ChocolateyPackages
    {
        public static string[] Packages => new[]
        {
            "7zip",
            "git",
            "oh-my-posh",
            "dotnet-6.0-sdk",
            "dotnet-sdk",
            "microsoft-windows-terminal",
            "notepadplusplus",
            "powertoys",
            "pwsh",
            "sysinternals",
            "sumatrapdf",
            "jetbrainstoolbox",
            "azure-cli",
            "dotnet",
            "docker-desktop",
            "linqpad",
            "postman",
            "vscode",
            "fnm",
            "ilspy",
            "neovim",
            "devtoys",
            "mobaxterm",
            "sharex",
            "vlc",
            "neovim",
            "gimp",
            "qbittorrent",
            "obsidian",
            "wiztree",
            "googleearthpro"
        };
    }
}
